[project]
name = "blender-llm-addin"
version = "0.1.0"
description = "AI integration for Blender to generate Blender API scripts based on user prompts"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
